language: python
dist: trusty
sudo: false
cache: pip
python: 3.5

install:
  - pip install .[ci] # Install TAF with CI deps

script:
  - pylint taf
  - bandit -c .bandit -r taf
  - coverage run --source taf tests/aggregate_tests.py
  # - coverage report -m --fail-under 99

after_success:
  - cd tests
  - coveralls
  - cd -

