language: python
dist: trusty
sudo: false
cache: pip
python: 3.6

env:
  - TOXENV=py35

before_script:
  - pip install pylint bandit tox

script:
  - pylint taf
  - bandit --ini tox.ini -r taf
  - tox

after_success:
  - cd tests
  - coveralls
  - cd -

